#!/bin/sh
# chkconfig: 2345 16 01
# description: forces a delay in further processing until hostname is correct

case "$1" in 
  start)
    ip_address=$(facter ipaddress)
    timestamp_now=$(date +%s)
    timestamp_later=$((timestamp_now + 300))

    # Wait until /etc/hosts has $ip_address OR timeout hits
    while ! grep $ip_address /etc/hosts > /dev/null; do
      [[ $(date +%s) -gt $timestamp_later ]] && exit 1
      sleep 1
    done

    # Get hostname from /etc/hosts, it's been set now
    hostname=$(grep $(facter ipaddress) /etc/hosts | cut -f 2)

    # Wait until hostname is set on box OR timeout hits
    while [ $(hostname) != $hostname ]; do
      [[ $(date +%s) -gt $timestamp_later ]] && exit 1
      sleep 1
    done

    chkconfig causeadelay off
    ;;
  *)
    echo "Usage: /etc/init.d/causeadelay {start}"
    exit 1
esac

exit 0
