#!/bin/sh
# chkconfig: 2345 16 01
# description: forces a delay in further processing until hostname is correct

case "$1" in 
  start)
    timestamp_now=$(date +%s)
    timestamp_later=$((timestamp_now + 300))
    hostname_shouldbe=$(xenstore-read vm-data/hostname)
    echo "[$timestamp_now] Starting up." >> /var/log/causeadelay.log

    # Wait until hostname is set on box
    while [ $(hostname) != $hostname_shouldbe ]; do
      if [ $(date +%s) -gt $timestamp_later ]; then
        echo "[$(date +%s)] It is now '$timestamp_later', timing out and exiting." >> /var/log/causeadelay.log
        exit 1
      else
        echo "[$(date +%s)] Hostname is still '$(hostname)', should be '$hostname_shouldbe', sleeping." >> /var/log/causeadelay.log
        sleep 15
      fi
    done
    
    echo "[$(date +%s)] All is good.  Disabling causeadelay for future runs." >> /var/log/causeadelay.log
    chkconfig causeadelay off
    ;;
  *)
    echo "Usage: /etc/init.d/causeadelay {start}"
    exit 1
esac

exit 0
